version: "3.8"

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=DentalApplication
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        container_name: postgres

    backend:
        build:
            context: .
            dockerfile: docker/Python/Dockerfile
        volumes:
            - .:/dentalapp
        ports:
            - "8000:8000"
        depends_on:
            - db
        container_name: dentalapplication_backend

    frontend:
        build:
            context: .
            dockerfile: docker/Vue/Dockerfile
        volumes:
            - .:/app
        ports:
            - "8080:8080"
        depends_on:
            - backend
        container_name: dentalapplication_frontend
