name: "Build docker images and deploy to Heroku."
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build, Push and Deploy to Heroku
              uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0 # use the latest version of the action
              with:
                  email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
                  api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
                  docker_compose_file: "./src/docker-compose.heroku.yml" # set the path to the folder where the docker-compose file is located
                  heroku_apps: '[
                    {"imagename":"frontend","appname":"${{ secrets.HEROKU_APPNAME }}","apptype":"web"},
                    {"imagename":"backend","appname":"${{ secrets.HEROKU_APPNAME }}","apptype":"web"},
                  ]'
