name: "Build docker images and deploy to Heroku."
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build, Push and Deploy to Heroku
              uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
              with:
                  email: ${{ secrets.HEROKU_EMAIL }}
                  api_key: ${{ secrets.HEROKU_API_KEY }}
                  docker_compose_file: "./docker-compose.yml"
                  '[{"imagename":"app1","appname":"app1","apptype":"web"},{"imagename":"app2","appname":"app2","apptype":"web"},{"imagename":"app3","appname":"app2","apptype":"worker"}]'